### ISSUE TITLE
Is there any way to trigger the download popups from the front/search page as well? 

### ISSUE THREAD

**Issue by i-am-at0m** [sk2589822/Exhentai-Enhancer#58]
Like how would this need to be changed to make that happen?

**Comment by sk2589822** [comment]
Hi, 
I didn't implement feature like this. I will take a look to see if this is feasible when I have time.

**Comment by sk2589822** [comment]
Hi @i-am-at0m 

I haven't started working on it yet, but I've given it some.

The way I've implemented the popups on the gallery page is as follows:
1. Preloading the torrents/direct download page.
2. Inserting the green check icon after the download link once the preloads are finished.
3. Showing the content when the user clicks the download link.

For the front page, I can add a direct download button (torrents download link already exists) to every gallery, but it's unrealistic to preload all the torrents/direct download pages on the front page.  
I believe it would make more sense to load them after the user clicks the download link and display the content once the download is finished.   
However, this method might be slower than what you experienced on the gallery page because it only starts downloading after you click the button.

I'm not sure if this approach is feasible, but I will find time to try it.

**Comment by i-am-at0m** [comment]
Agreed, preloading that sounds like mess. Honestly being slow isn't the
worst if it means I don't have to click into the gallery to bring up the
downloads prompt.

**Comment by sk2589822** [comment]
Hi @i-am-at0m,

I've just completed this feature.   
However, I'm unable to test if it works as expected because my H@H was revoked a while ago.
So Let me know if there are any issues, thanks!

**Comment by i-am-at0m** [comment]
Doesn't look like it. One of the times I loaded while switching views I saw a bunch of little A buttons in thumbnail view but haven't seen them again since. And when I tried to click, I got a yellow banner saying the link didn't exist., tried to refresh and they disappeared

Running 1.12 on Firefox nightly on Android.

**Comment by sk2589822** [comment]
Have you logged in your account? I use the e-hentai API for getting the content of download page, which required a logged in cookie.

I've also fix a issue in 1.12.1 about using incorrect API for e-hentai (didn't notice it because I usually use exhentai).   
Not sure if you were visiting e-hentai or exhentai.

If it still not works after logged in & update to 1.12.1. Can you try it on a PC to see if it's work?

---

The warning toast (yellow banner) will only shows when
1. set `Action when clicking "Archive Download"` to  `download 2400x Resolution with H@H`.
  ![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/25762718/8afbf897-bc17-4547-8653-b307ccae2dbf)
3. the 2400x option is N/A H@H.

After showing warning toast, the archiver download popup should shows as well.

**Comment by i-am-at0m** [comment]
In 1.12.0:
Quality is set to send original to ***@***.*** and works elsewhere.
I do use e-h so that might be a reason
Warning toast has text implying it's got a link to open the prompt but
nothing happened even I tried to click it.

Won't have time to check 1.12.1 until a bit later from mobile or pc

**Comment by i-am-at0m** [comment]
Just wanted to follow up, 1.12.1 isn't working for me either for this feature.

**Comment by sk2589822** [comment]
Could you provide more information like browser, browser version, OS, error messages in devtools console, etc.?

A video with your operation is even better.

**Comment by AlexanderHel** [comment]
wonder if the same can do for rating

**Comment by i-am-at0m** [comment]
Looks like the little A to trigger this only pops up in thumbnail view.
Anything else and it isn't there. But it does work in that view.

**Comment by sk2589822** [comment]
> wonder if the same can do for rating

Sorry @AlexanderHel, since I don't typically use rating function, I don't intend to implement this feature.

**Comment by sk2589822** [comment]
@i-am-at0m 

> Looks like the little A to trigger this only pops up in thumbnail view.

Yes, all of the features in this script were built based on thumbnail view which I usually used.  
Like I mentioned [here](https://github.com/sk2589822/Exhentai-Enhancer?tab=readme-ov-file#front-page-enhancer)

![image](https://github.com/sk2589822/Exhentai-Enhancer/assets/25762718/1db92592-0369-4c20-84bd-38c07f4f041a)

**Comment by sk2589822** [comment]
close by fb33d56c46d96b0bb5f882b75092f9e7aaa5c1a9
